source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'LGKnowledgeFramework_Example' do
  pod 'LGKnowledgeFramework', :path => '../'

  target 'LGKnowledgeFramework_Tests' do
    inherit! :search_paths

    
  end
end
